export enum PAGES {
    SETTINGS = 'SETTINGS',
    QUIZ = 'QUIZ',
    FAVORITES = 'FAVORITES',
    INFO = 'INFO'
}

export enum LEVEL {
    BASIC = 'BASIC',
    ELEMENTARY = 'ELEMENTARY',
    PRE_INTERMEDIATE = 'PRE_INTERMEDIATE',
    INTERMEDIATE = 'INTERMEDIATE',
    VERBS = 'VERBS',
    UPPER_INTERMEDIATE = 'UPPER_INTERMEDIATE'
}
